name: karate demo

on:
  push:
    branches: [main]
  schedule:
   - cron: "*/2 * * * *"
   
    
jobs:
   
   build:
    runs-on: windows-latest 
 
    
    outputs:
      output1: ${{ steps.package.outputs.data }}
 
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
      - name: Run command
        run: mvn clean test "-DconfigPath=qa.yaml" "-Dtags=@updatePetDetailsById"
     
      - name: Pare Integration Test Results
        id: ParseResult
        run: |
         $resultsFile = 'results-json.txt'
         $resultPath = './target/surefire-reports/results-json.txt'
         echo = "$resultPath"
         $resultJson = Get-Content $resultPath | ConvertFrom-Json -Depth 4
         $testFailures = $resultJson.passed
         echo "testFailures=$testFailures" | out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
         if(($resultPath) && ($testFailures -ge 0)){
         echo "$testFailures"
         }
         
         
      - name: store in a variable
        id: package
        run: |
         echo "::set-output name=data::$testFailures"
      
      - name: Echo outputs
        run: echo ${{needs.build.outputs.data}}
       
         
   display:
    runs-on: windows-latest 
    needs: build
    steps:
     - run: echo ${{needs.build.outputs.data}}

                
        
  
  
     
       
 
