name: karate demo

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    outputs:
      output1: ${{ steps.contents.outputs.data }}
  
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
      - name: Run command
        run: mvn clean test "-DconfigPath=qa.yaml" "-Dtags=@updatePetDetailsById"
      
      - name: Read Text File
        id: contents
        run: |
         contents=$(cat results-json.txt)
         echo "::set-output name=data::$contents"
   
  
  display:
     runs-on: windows-latest
     needs: build
    
     steps:
      - run: echo ${{needs.build.outputs.output1}}
     

 
