name: karate demo

on:
  push:
    branches: [main]
  schedule:
   - cron: "*/2 * * * *"
    
jobs:
  build:
    runs-on: windows-latest 
    
    outputs:
      output1: ${{ steps.package.outputs.test }}
   
   
   
  
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
      - name: Run command
        run: mvn clean test "-DconfigPath=qa.yaml" "-Dtags=@updatePetDetailsById"
     
     
        
  display:
    runs-on: windows-latest 
    
    outputs:
      output1: ${{ steps.package.outputs.test }}
  
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
          
      - name: Build with Maven
        run: mvn -B package --file pom.xml
        
      - name: Run command
        run: mvn clean test "-DconfigPath=qa.yaml" "-Dtags=@updatePetDetailsById"
     
       
 
