name: karate demo

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
  
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: Run command
        run: mvn clean test "-DconfigPath=qa.yaml" "-Dtags=@updatePetDetailsById"
      
      - name: Read results-json.txt
        id: package
        uses: juliangruber/read-file-action@v1
        with:
          path: ./target/surefire-reports/results-json.txt
     
      - name: Echo results-json.txt

      - id: step1
        run: echo "::set-output name=test::steps.package.outputs.content"
  
  display:
     runs-on: windows-latest
     needs: build
    
     steps:
      - run: echo ${{needs.build.outputs.output1}}
     

 
