name: Read another yaml demo

on:
 push:
    branches: [main]
 
jobs:
  
 display:
   runs-on: windows-latest  
   steps:
        - uses: ./.github/workflows/blank.yml
        - run: |
           echo ${{ jobs.build.package.data }}
           echo "Hello"
